<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>22285snake_98774.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="22285snake_98774.ico" />
  </ItemGroup>

</Project>
